Repository A-kirami/matcha, pull requests merged in 2023-08, with the labels that each got.

#116 ⬆️ Update tauri-apps
  package.json
  pnpm-lock.yaml
Labels: dependencies

#118 🐛 修复群禁言通知没有区分开关状态的问题
  src/components/ChatNotice.vue
Labels: bug

#120 💄 去除原始事件底部空白边距
  src/style.css
Labels: UI/UX

#94 ✨ 添加聊天消息右键菜单
  package.json
  pnpm-lock.yaml
  src/components/ChatBox.vue
  src/components/ChatInput.vue
  src/components/ChatMessage.vue
  src/components/MessageContent.vue
  src/main.ts
  src/router/index.ts
  src/stores/index.ts
  src/stores/session.ts
  src/style.css
  src/styles/contextmenu.css
  unocss.config.ts
Labels: enhancement

#121 ✨ 支持自动选择未占用的端口
  src-tauri/src/server.rs
  src-tauri/src/utils.rs
Labels: enhancement

#125 🐛 创建用户修改名称以及id时光标跳转
  src/components/CreateUserForm.vue
Labels: bug
