Repository A-kirami/matcha, pull requests merged in 2024-04, with the labels that each got.

#167 💄 设置表单添加动画效果
  src/views/settings/connect.vue
Labels: UI/UX

#171 ✨ 允许配置连接错误显示
  src/driver/websocket-client/index.ts
  src/stores/connect-settings.ts
  src/views/settings/connect.vue
Labels: enhancement

#172 🐛 修复断开连接时自动重连没有停止的问题
  src/driver/websocket-client/index.ts
Labels: bug

#173 ✨ 添加聊天栏头部按钮提示
  src/components/chat/ChatBoxHeader.vue
Labels: enhancement

#175 🐛 修复macos下的状态栏显示
  src/components/AppSidebar.vue
  src/components/ui/controls/WindowControls.vue
Labels: bug
